name: Run Tests

on:
  pull_request:
    branches:
      - main # Replace "main" with the name of your default branch, if different.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Update pnpm
        run: pnpm add -g pnpm

      - name: Run tests
        run: pnpm test
